name: 'Release'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'manifests/base/kustomization.yaml'
    tags-ignore:
      - '*'

jobs:
  code-validation:
    uses: ./.github/workflows/code_validation.yml

  release:
    needs: [code-validation]
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
