name: 'Release'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'manifests/base/kustomization.yaml'
    tags-ignore:
      - '*'

jobs:
  code-validation:
    uses: ./.github/workflows/code_validation.yml

  release:
    needs: [code-validation]
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    env:
      HUSKY: 0

    steps:
      - name: Get Octo-sts token
        uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: 'liatrio/react-dora-charts'
          identity: semantic-release

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Setup node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn rollup

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/octo-sts[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
          
      - name: Bump and Release
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: octo-sts[bot]
          GIT_AUTHOR_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+octo-sts[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: octo-sts[bot]
          GIT_COMMITTER_EMAIL: ${{ steps.get-user-id.outputs.user-id }}+octo-sts[bot]@users.noreply.github.com
        run: npx semantic-release
