name: 'Release'
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'manifests/base/kustomization.yaml'
    tags-ignore:
      - '*'

jobs:
  code-validation:
    uses: ./.github/workflows/code_validation.yml

  release:
    needs: [code-validation]
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    env:
      HUSKY: 0

    steps:
      - name: Generate Token with Octo-STS
        id: octo-sts
        uses: octo-sts/action@210248e8ae1ae1550aa6e232c6f192b3ccbf7335
        with:
          scope: "liatrio/react-dora-charts"
          identity: semantic-release

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn rollup

      - name: Get GitHub App User ID for octo-sts[bot]
        id: get-user-id
        run: echo "user_id=$(gh api "/users/octo-sts[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}

      - name: Configure Git User
        run: |
          git config --global user.name "octo-sts[bot]"
          git config --global user.email "${{ steps.get-user-id.outputs.user_id }}+octo-sts[bot]@users.noreply.github.com"

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
